### ISSUE TITLE
Available build

### ISSUE THREAD

**Issue by jimbobmcgee** [duncansmart/sqlpipe#1]
Any chance you have a build of this lying around, that you could upload/link for posterity?  
I'm not a C++ guy, and have not got a C++ compiler to hand...

Cheers.

**Comment by duncansmart** [comment]
Here you go: https://github.com/duncansmart/sqlpipe/releases/download/v1.0/SqlPipe.zip

**Comment by jimbobmcgee** [comment]
Thanks, Duncan; much appreciated.
