### ISSUE TITLE
Can you provide the "binary" ? 

### ISSUE THREAD

**Issue by foxontherock** [duncansmart/sqlpipe#4]
Hi, I really like your software and I built it from visual studio 2015.  But, I am sure that lot of tech people who manage databases doesn't know anything about visual studio or c++ compilation... 

For them, I think that if you provide a /binary folder with a working exe, your project will gain popularity! 

Very nice to backup directly to 7z, it gives an average 4:1 ratio for our databases, like if we use "with compression" option, but we can't use "with compression" with express-web-standard editions of SQL server, so your tool really helps get smaller .BAK files directly, without intermediate.

**Comment by duncansmart** [comment]
There's a ZIP in releases https://github.com/duncansmart/sqlpipe/releases. Bear in mind that restore doesn't work currently, only backup.

**Comment by foxontherock** [comment]
Oh! I just learned something about github! I tought that the "release" tab was something else... :+1:

**Comment by duncansmart** [comment]
I updated the readme, hopefully that will help future users :-)
